### ISSUE TITLE
[Question]: Is there some way to easily map the source to its reference translation for the Google MQM Dataset?

### ISSUE THREAD

**Issue by alvations** [google/wmt-mqm-human-evaluation#11]
Details on https://stackoverflow.com/questions/73922895/is-there-some-way-to-easily-map-the-source-to-its-reference-translation-for-the

I've tried this but looks like I'm still missing ~20% of the data to their references: https://www.kaggle.com/code/alvations/lightyear2

**Comment by freitagmarkus** [comment]
Hi!

The mqm files contain doc_name doc_id ans seg_id. Did you try to use these fields?

**Comment by alvations** [comment]
Thanks for the pointers on the doc_name and doc_id, and also on the tweets. I think there's still some minor things like `<v>` that needs to be cleaned out to get the exact source-target pairs. I guess it's easier to use the https://github.com/google-research/mt-metrics-eval data for my purpose. 

Thank you again for the answer and pointers!
