### ISSUE TITLE
Source-Side Spans

### ISSUE THREAD

**Issue by jvamvas** [google/wmt-mqm-human-evaluation#2]
Thank you for creating this amazing resource!
The annotator guidelines (Table 12 of your paper) contain the following instruction:

> To identify an error, highlight the relevant span of text [...] The span of text may be in the source segment if the error is a source error or an omission.

In the dataset, all the spans are on the target side, including omission errors:
```
Source: Setting the example? Income inequality in the US is at an all-time high
Target: <v>Die</v> Einkommensungleichheit in den USA ist auf einem Allzeithoch
Category: Accuracy/Omission 
```

I'm wondering: Did the annotators deviate from the guidelines in this respect, or is it maybe a data processing mistake that could still be fixed?

**Comment by freitagmarkus** [comment]
Hi,

In one of our data cleaning steps, we did remove the annotations from the source side. If needed, I can re-add the error span to the source sentences? Let mw know if this is what you are looking for and I will work on that.

Markus

**Comment by jvamvas** [comment]
Hi Markus,

Yes, the error span in the source, where available, would indeed by very useful for a project I am currently working on.

If it's easier for you, you could also send me the raw data from before that cleaning step, and I will work on a pull request.

Best,
Jannis

**Comment by freitagmarkus** [comment]
Hi,

I am trying to add these at the end of this week.

Markus

**Comment by SAI990323** [comment]
> 

Hi, Markus

I find that the omission errors in newstest2020 are still labeled on the target side, have you re-add the error span to the source sentences?

**Comment by freitagmarkus** [comment]
I added the source erros as additional files to the WMT20 directories.

The source errors were also annotated on the target side. I am not sure why the annotators decided to do so. Hope that helps.
