### ISSUE TITLE
Minor inconsistencies in the data

### ISSUE THREAD

**Issue by jvamvas** [google/wmt-mqm-human-evaluation#4]
Thanks again for creating this great resource. I noticed some minor inconsistencies in the newstest2020 dataset that could be relevant for other people working with it:

**Traces of Post-Editing**
The raters did not just highlight error spans (as indicated by the guidelines) but also seem to have made post-edits. The "target" column sometimes contains text that deviates from the original translation. This affects 8255 out of 79020 ratings for EN–DE and 32184 out of 124292 ratings for ZH–EN.
Example:
```
ID: Human-A.0 | independent.281139 | 4 | 4
Rater: rater2
Original translation: Um auf Titelseiten zu gelangen, trug er einen Mundschutz und klebte sich Klebeband auf seine Nase, um Leute zum Reden zu bringen.
Target in the dataset: Um auf Titelseiten zu gelangen, trug <v>er angeblich </v> einen Mundschutz und klebte sich Klebeband auf seine Nase, um Leute zum Reden zu bringen.
```

**Superfluous Quotes**
A few translations are wrapped in quotes that are not present in the original data. The raters have usually marked the quotes as addition or punctuation errors, which has slightly increased the error count for these types. This affects at least 135 out of 14180 samples for EN–DE and 25 out of 19994 samples for ZH–EN.
Example:
```
ID: Online-A.1574 | stv.tv.21636 | 17 | 77
Original source: "This review is focused on steps that can be taken to help aid enforcement agencies such as local authorities, as they use their powers to help keep communities safe."
Source in the dataset: ""This review is focused on steps that can be taken to help aid enforcement agencies such as local authorities, as they use their powers to help keep communities safe.""
Original translation: "Diese Überprüfung konzentriert sich auf Maßnahmen, die ergriffen werden können, um Durchsetzungsbehörden wie lokalen Behörden zu helfen, da sie ihre Befugnisse nutzen, um die Sicherheit der Gemeinschaften zu gewährleisten."
Target in the dataset: """Diese Überprüfung konzentriert sich auf Maßnahmen, die ergriffen werden können, um Durchsetzungsbehörden wie lokalen Behörden zu helfen, da sie ihre Befugnisse nutzen, um die Sicherheit der Gemeinschaften zu gewährleisten."""
```

**Comment by gsarti** [comment]
Hi and thank you for the amazing resource. On top of the inconsistencies mentioned by @jvamvas, I would like to report that rows 59831 and 103979 of [`mqm_newstest2020_zhen.tsv`](https://github.com/google/wmt-mqm-human-evaluation/blob/main/newstest2020/zhen/mqm_newstest2020_zhen.tsv) are missing the target sentence.

**Comment by freitagmarkus** [comment]
Hi,
 @gsarti I fixed the two lines that you mentioned.

@jvamvas You are correct. Sometimes raters postedited the output even though they were not asked to. We updated our interface and the new data (newstest2021 and tedtalk) should not have similar issues. Feel free to clean up the data and we can update the data here.

Thanks,
Markus
