### ISSUE TITLE
Data missing in mqm_newstest2020_zhen.tsv

### ISSUE THREAD

**Issue by xu1998hz** [google/wmt-mqm-human-evaluation#5]
I found out mqm_newstest2020_zhen.tsv has minor data missing issue for the following systems at Seg ID 181.
181 Online-B.1605
181 WeChat_AI.1525
181 Tencent_Translation.1249
181 THUNLP.1498
181 OPPO.1422
181 Huoshan_Translate.919
This caused a mismatch in between mqm_newstest2020_zhen.tsv and mqm_newstest2020_zhen.avg_seg_scores.tsv
mqm_newstest2020_zhen.tsv only has 19994 unique system+id.

**Comment by freitagmarkus** [comment]
Hi xu1998hz,

Sorry for the slow response. I just had time to look into this and I can actually not reproduce the issue. For all 10 systems, we have ratings from 3 different raters for seg id 181. See below bash command:

cat mqm_newstest2020_zhen.tsv | cut -f 1-5 | grep 181 | grep chinanews.com.102535 | sort -u
DeepMind.381	chinanews.com.102535	22	181	rater3
DeepMind.381	chinanews.com.102535	22	181	rater4
DeepMind.381	chinanews.com.102535	22	181	rater6
DiDi_NLP.401	chinanews.com.102535	22	181	rater3
DiDi_NLP.401	chinanews.com.102535	22	181	rater4
DiDi_NLP.401	chinanews.com.102535	22	181	rater6
Human-A.0	chinanews.com.102535	22	181	rater3
Human-A.0	chinanews.com.102535	22	181	rater4
Human-A.0	chinanews.com.102535	22	181	rater6
Human-B.0	chinanews.com.102535	22	181	rater3
Human-B.0	chinanews.com.102535	22	181	rater4
Human-B.0	chinanews.com.102535	22	181	rater6
Huoshan_Translate.919	chinanews.com.102535	22	181	rater3
Huoshan_Translate.919	chinanews.com.102535	22	181	rater4
Huoshan_Translate.919	chinanews.com.102535	22	181	rater6
Online-B.1605	chinanews.com.102535	22	181	rater3
Online-B.1605	chinanews.com.102535	22	181	rater4
Online-B.1605	chinanews.com.102535	22	181	rater6
OPPO.1422	chinanews.com.102535	22	181	rater3
OPPO.1422	chinanews.com.102535	22	181	rater4
OPPO.1422	chinanews.com.102535	22	181	rater6
Tencent_Translation.1249	chinanews.com.102535	22	181	rater3
Tencent_Translation.1249	chinanews.com.102535	22	181	rater4
Tencent_Translation.1249	chinanews.com.102535	22	181	rater6
THUNLP.1498	chinanews.com.102535	22	181	rater3
THUNLP.1498	chinanews.com.102535	22	181	rater4
THUNLP.1498	chinanews.com.102535	22	181	rater6
WeChat_AI.1525	chinanews.com.102535	22	181	rater3
WeChat_AI.1525	chinanews.com.102535	22	181	rater4
WeChat_AI.1525	chinanews.com.102535	22	181	rater6

Let me know if you still see a problem,
Markus

**Comment by xu1998hz** [comment]
Thanks for your response!
