### ISSUE TITLE
avg_seg_scores for 2021?

### ISSUE THREAD

**Issue by jbgruenwald** [google/wmt-mqm-human-evaluation#6]
Hi, I saw in 2020 you published sentence scores and they were really helpful for me. Thanks for that :)

I couldn't find theses scores for 2021 in the repo. Could you provide them? Or do you have the script to calculate them from the MQM evaluations. It would be of great help, Thanks

**Comment by freitagmarkus** [comment]
Hi,

I just uploaded the avg_seg_scores for newstest2021 and ted talks. Please double check that the numbers match the one in the WMT21 Metric Task paper.

Thanks and let me know if you have other questions.

Markus
